DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS bookings;
DROP TABLE IF EXISTS items;
DROP TABLE IF EXISTS item_requests;
DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255)                            NOT NULL,
    email VARCHAR(512)                            NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS item_requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    requester_id BIGINT REFERENCES users (id)            NOT NULL,
    description  VARCHAR(255)                            NOT NULL,
    created      TIMESTAMP                               NOT NULL,
    CONSTRAINT item_requests_pk PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS items
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description VARCHAR(2048)                           NOT NULL,
    user_id     BIGINT REFERENCES users (id)            NOT NULL,
    request_id  BIGINT REFERENCES item_requests (id),
    available   BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_items PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS bookings
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    booker_id  BIGINT REFERENCES users (id)            NOT NULL,
    item_id    BIGINT REFERENCES items (id)            NOT NULL,
    status     VARCHAR(48)                             NOT NULL,
    start_time TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    end_time   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_bookings PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS comments
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    item_id BIGINT REFERENCES items (id)            NOT NULL,
    user_id BIGINT REFERENCES users (id)            NOT NULL,
    text    VARCHAR(2048)                           NOT NULL,
    created TIMESTAMP WITHOUT TIME ZONE             NOT NULL
);